<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aleksei Semenchenko. Profile</title>
 </head>
<body>

    <h1 style="text-align: center; color: darkblue;" >Aleksei Semenchenko profile</h1>
    <h2>Contacts</h2>
    <pre>
        • aleksei.semenchenko@outlook.com • +420 776 203 113
        • linkedin.com/in/alekseisemenchenko • Prague, CZ, 19017
    </pre>

</body>
</html>
